stages:
  - build
  - test

before_script:
  - export PATH=$PATH:/usr/local/go/bin
  - export GOPATH=$HOME/gopath

build:
  stage: build
  script:
    - make

test:
  stage: test
  script:
    - make
    - ./tests/test
