#!/bin/bash

# Colour Codes
RED='\033[0;31m'   # Red
LRED='\033[1;31m'  # Light Red
GREEN='\033[1;32m' # Green
BROWN='\033[0;33m' # Brown
CYAN='\033[0;36m'  # Cyan
NC='\033[0m'       # White

# Default path to example files
DEFAULT_PATH="docs/examples"

# Check if a specific path provided, if not use default
if [ $# -eq 0 ]; then
  EXAMPLES_PATH=$DEFAULT_PATH
else
  EXAMPLES_PATH=$1
fi

# Subdirectories for Valid and Invalid cases
VALID="$EXAMPLES_PATH/valid"

n=0
FAIL=0
PASS=0



# Function to test the input file
testResult() {
  find $1 -name '*.wacc' | while read fW;
  do
    OUT="$n:${GREEN} $PASS${RED} $FAIL${BROWN} File: ${CYAN}${fW#*$1}${NC} : "
    n=$(($n+1))
    IN="$(echo "$fW" | sed 's/\.wacc/.in/')"
    if [[ $fW == *"advanced"* ]]; then
      continue
    fi
    if [ -e $IN ]; then
      INPUT=$IN
    else 
      INPUT="/dev/null"
    fi
 
    docs/refCompile -x $fW < $INPUT > refResult.txt
    sed -i '0,/^[=]\+/d' refResult.txt
    sed -i '$ d' refResult.txt
    sed -i '$ d' refResult.txt
    sed -i '$ d' refResult.txt
    sed -i '$ d' refResult.txt
    sed -i 's/0x[a-f0-9]\+/0x/g' refResult.txt

    ./compile $fW
    fW="$(basename $fW)"
    f="$(echo $fW | sed 's/\.wacc//')"
    fs=$f".s"
    
    arm-linux-gnueabi-gcc -o $f -mcpu=arm1176jzf-s -mtune=arm1176jzf-s $fs
    qemu-arm -L /usr/arm-linux-gnueabi/ $f < $INPUT > result.txt 
    sed -i 's/0x[a-f0-9]\+/0x/g' result.txt

    DIFF="$(diff result.txt refResult.txt)"
    # Print the result on test failure
    if [ -z "$DIFF" ]; then
      RESULT="${GREEN}Pass${NC}"
      PASS=$(($PASS+1))
    else
      RESULT="${RED}Fail${NC}"
      FAIL=$(($FAIL+1))
      echo "-------- EXPECTED --------"
      cat refResult.txt
      echo "----------  GOT ----------"
      cat result.txt
      echo "------- DIFFERENCE -------"
      diff result.txt refResult.txt
    fi
    rm $f
    rm $fs
    echo -e "$OUT $RESULT"
  done
  rm refResult.txt
  rm result.txt
}

# Start Testing
echo -e "${GREEN}===== WACC Compiler Testing${NC}"

# Test Valid Cases
echo -e "${LRED}----- Valid Testcases${NC}"
testResult $VALID

# Testing Complete
echo -e "${GREEN}===== Testing Complete${NC}"
