#!/bin/bash

echo -e "---------- WACC Compiler Testing ----------"

RED='\033[0;31m'
LRED='\033[1;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

DEFAULT_PATH="docs/examples"

if [ $# -eq 0 ]; then
  EXAMPLES_PATH=$DEFAULT_PATH
else
  EXAMPLES_PATH=$1
fi

INVALID_SYNTAX="$EXAMPLES_PATH/invalid/syntaxErr"
INVALID_SEMANTIC="$EXAMPLES_PATH/invalid/semanticErr"
VALID="$EXAMPLES_PATH/valid"


testFiles() {
  find $1 -name '*.wacc' | while read f;
  do
    OUT=$OUT"${BROWN}File: ${CYAN}${f#*$1}${NC} : "

    echo -e "File: $f " >> log.txt 2>&1
    ./compile $f >> log.txt 2>&1

    if [ $? == $2 ]; then
      RESULT="${GREEN}Pass${NC}"
    else
      RESULT="${RED}Fail${NC}"
    fi

    OUT=$OUT" $RESULT"

    echo -e"Result: $RESULT " >> log.txt 2>&1
    echo -e $OUT

    OUT=""
  done

  rm log.txt
}

echo -e "\n${LRED}===== Valid Testcases =====${NC}"
testFiles $VALID 0

echo -e "\n${LRED}===== Invalid Tescases - Syntax Error =====${NC}"
testFiles $INVALID_SYNTAX 100

echo -e "\n${LRED}===== Invalid Tescases - Semantic Error =====${NC}"
testFiles $INVALID_SEMANTIC 200

echo -e "---------- Testing Complete ----------"
