#!/bin/bash

RED='\033[0;31m'
LRED='\033[1;31m'
GREEN='\033[1;32m'
BROWN='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

DEFAULT_PATH="docs/examples"

if [ $# -eq 0 ]; then
  EXAMPLES_PATH=$DEFAULT_PATH
else
  EXAMPLES_PATH=$1
fi

INVALID_SYNTAX="$EXAMPLES_PATH/invalid/syntaxErr"
INVALID_SEMANTIC="$EXAMPLES_PATH/invalid/semanticErr"
VALID="$EXAMPLES_PATH/valid"


testFiles() {
  find $1 -name '*.wacc' | while read f;
  do
    PASSED=0
    OUT=$OUT"${BROWN}File: ${CYAN}${f#*$1}${NC} : "

    echo -e "File: $f " >> log.txt 2>&1
    ./compile $f >> log.txt 2>&1

    if [ $? != $2 ]; then
      RESULT="${RED}Fail${NC}"
      PASSED=1
      OUT=$OUT" $RESULT"

      echo -e"Result: $RESULT " >> log.txt 2>&1
      echo -e $OUT
    fi

    OUT=""
  done

  rm log.txt
}

echo -e "${GREEN}===== WACC Compiler Testing${NC}"

echo -e "${LRED}----- Valid Testcases${NC}"
testFiles $VALID 0

echo -e "${LRED}----- Invalid Tescases - Syntax Error${NC}"
testFiles $INVALID_SYNTAX 100

echo -e "${LRED}----- Invalid Tescases - Semantic Error${NC}"
testFiles $INVALID_SEMANTIC 200

echo -e "${GREEN}===== Testing Complete${NC}"
