#!/bin/bash

# Colour Codes
RED='\033[0;31m'   # Red
LRED='\033[1;31m'  # Light Red
GREEN='\033[1;32m' # Green
BROWN='\033[0;33m' # Brown
CYAN='\033[0;36m'  # Cyan
NC='\033[0m'       # White

# Default path to example files
DEFAULT_PATH="docs/examples"

# Subdirectories for Valid and Invalid cases
INVALID_SYNTAX="$DEFAULT_PATH/invalid/syntaxErr"
INVALID_SEMANTIC="$DEFAULT_PATH/invalid/semanticErr"
VALID="$DEFAULT_PATH/valid"

#-------------
# FLAGS
#-------------

FRONTEND=true
BACKEND=true
PROGRESS=false

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
      -nof|--no-frontend)
      FRONTEND=false
      ;;
      -nob|--no-backend)
      BACKEND=false
      ;;
      -p|--progress)
      PROGRESS=true
      ;;
      *)
              # unknown option
      ;;
  esac

  shift # past argument or value
done

#------------------------
# TEST FRONTEND FUNCTION
#------------------------

# Function to test the input file
testFrontend() {

  nF=0
  #calculate total number of files
  TOTFILES=$(find $1 -name '*.wacc' | wc -l)

  while read f; do

    #create PROGRESS BAR
    #calculate percentage
    nF=$(($nF+1))
    #x=2
    #nFP=$(( nFP / x ))

    if [ "$PROGRESS" = true ]; then
      echo -ne "($nF/$TOTFILES)\r"
    fi

    fs="$(echo $f | sed 's/\.wacc/.s/')"

    OUT=$OUT"${BROWN}File: ${CYAN}${f#*$1}${NC} : "

    echo -e "File: $f " >> log.txt 2>&1

    # Run compile script for the input file
    ./compile $f >> log.txt 2>&1

    # Print the result on test failure
    if [ $? != $2 ]; then
      RESULT="${RED}Fail${NC}"
      OUT=$OUT" $RESULT"

      echo -e"Result: $RESULT " >> log.txt 2>&1
      echo -e $OUT
      RETURN=1
    fi
    if [ "$1" == "$VALID" ]; then
      fs=$(basename $fs)
      rm -f $fs
    fi
    OUT=""
  done < <(find $1 -name '*.wacc')

  rm -f log.txt
  return $RETURN
}

#------------------------
# TEST BACKEND FUNCTION
#------------------------

testBackend() {

# Counters

  nB=0
  FAIL=0
  PASS=0

  #calculate total number of files
  TOTFILESB=$(find $1 -name '*.wacc' | wc -l)

  while read fW; do

    #create PROGRESS BAR
    #calculate percentage
    nB=$(($nB+1))
    #x=2
    #nBP=$(( $nBi / x ))

    if [ "$PROGRESS" = true ]; then
      #print progress bar
      echo -ne "($nB/$TOTFILESB)\r"
    fi


    OUT="$nB:${GREEN} $PASS${RED} $FAIL${BROWN} File: ${CYAN}${fW#*$1}${NC} : "
    IN="$(echo "$fW" | sed 's/\.wacc/.in/')"
    if [[ $fW == *"advanced"* ]]; then
      continue
    fi
    if [ -e $IN ]; then
      INPUT=$IN
    else
      INPUT="/dev/null"
    fi

    ./compile $fW
    f="$(basename $fW)"
    f="${f%.wacc}"
    fs=$f".s"

    arm-linux-gnueabi-gcc -o $f -mcpu=arm1176jzf-s -mtune=arm1176jzf-s $fs
    qemu-arm -L /usr/arm-linux-gnueabi/ $f < $INPUT > result.txt
    LOCALEXIT=$?
    REFEXIT=$(cat ${fW%.wacc}.refexit)
    sed -i 's/0x[a-f0-9]\+/0x/g' result.txt

    DIFF="$(diff result.txt ${fW%.wacc}.refout)"
    # Print the result on test failure
    if [ "$LOCALEXIT" -ne "$REFEXIT" ]; then
      RESULT="${RED}Fail${NC}"
      FAIL=$(($FAIL+1))
      echo "-------- EXPECTED --------"
      echo "Exit code ${REFEXIT}"
      echo "----------  GOT ----------"
      echo "Exit code ${LOCALEXIT}"
      echo -e "$OUT $RESULT"
      RETURN=1
    elif [ -n "$DIFF" ]; then
      RESULT="${RED}Fail${NC}"
      FAIL=$(($FAIL+1))
      echo "-------- EXPECTED --------"
      cat ${fW%.wacc}.refout
      echo "----------  GOT ----------"
      cat result.txt
      echo "------- DIFFERENCE -------"
      diff result.txt ${fW%.wacc}.refout
      echo -e "$OUT $RESULT"
      RETURN=1
    else
      RESULT="${GREEN}Pass${NC}"
      PASS=$(($PASS+1))
      if [ "$SHOWPASS" = true ]; then
        echo -e "$OUT $RESULT"
      fi
    fi
    rm -f $f
    rm -f $fs

    ### Test optimised code

    ./wacc_34 -optimise -file $fW
    f="$(basename $fW)"
    f="${f%.wacc}"
    fs=$f".s"

    arm-linux-gnueabi-gcc -o $f -mcpu=arm1176jzf-s -mtune=arm1176jzf-s $fs
    qemu-arm -L /usr/arm-linux-gnueabi/ $f < $INPUT > result.txt
    LOCALEXIT=$?
    REFEXIT=$(cat ${fW%.wacc}.refexit)
    sed -i 's/0x[a-f0-9]\+/0x/g' result.txt

    DIFF="$(diff result.txt ${fW%.wacc}.refout)"
    # Print the result on test failure
    if [ "$LOCALEXIT" -ne "$REFEXIT" ]; then
      RESULT="${RED}Optimised Fail${NC}"
      FAIL=$(($FAIL+1))
      echo "-------- EXPECTED --------"
      echo "Exit code ${REFEXIT}"
      echo "----------  GOT ----------"
      echo "Exit code ${LOCALEXIT}"
      echo -e "$OUT $RESULT"
      RETURN=1
    elif [ -n "$DIFF" ]; then
      RESULT="${RED}Optimised Fail${NC}"
      FAIL=$(($FAIL+1))
      echo "-------- EXPECTED --------"
      cat ${fW%.wacc}.refout
      echo "----------  GOT ----------"
      cat result.txt
      echo "------- DIFFERENCE -------"
      diff result.txt ${fW%.wacc}.refout
      echo -e "$OUT $RESULT"
      RETURN=1
    else
      RESULT="${GREEN}Optimised Pass${NC}"
      PASS=$(($PASS+1))
      if [ "$SHOWPASS" = true ]; then
        echo -e "$OUT $RESULT"
      fi
    fi
    rm -f $f
    rm -f $fs
  done < <(find $1 -name '*.wacc')
  rm -f result.txt
  rm -f *.core
  return $RETURN
}

EXITCODE=0

# Start Testing
echo -e "${GREEN}===== WACC Compiler Testing${NC}"

#----------------------------
# Test Frontend
#----------------------------
if [ "$FRONTEND" = true ]; then
  echo -e "${GREEN}===== FRONTEND Testing"
  # Test Valid Cases
  echo -e "${LRED}----- Valid Testcases${NC}"
  if ! testFrontend $VALID 0; then
    EXITCODE=$((EXITCODE + 1))
  fi

  # Test Syntactically Invalid Cases
  echo -e "${LRED}----- Invalid Testcases - Syntax Error${NC}"
  if ! testFrontend $INVALID_SYNTAX 100; then
    EXITCODE=$((EXITCODE + 2))
  fi

  # Test Semantically Invalid Cases
  echo -e "${LRED}----- Invalid Testcases - Semantic Error${NC}"
  if ! testFrontend $INVALID_SEMANTIC 200; then
    EXITCODE=$((EXITCODE + 4))
  fi
fi

#----------------------------
# Test Backend
#----------------------------

if [ "$BACKEND" = true ]; then
  echo -e "${GREEN}===== BACKEND Testing${NC}"
  # Test Valid Cases
  echo -e "${LRED}----- Valid Testcases${NC}"
  if ! testBackend $VALID; then
    EXITCODE=$((EXITCODE + 8))
  fi
fi

# Testing Complete
echo -e "${GREEN}===== Testing Complete${NC}"
exit $EXITCODE
